# Installed by `agent-repos completions fish --install`.
# This shim sources completions generated by the CLI so they stay up to date.
if type -q agent-repos
    agent-repos completions fish | source
end
