package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// trackedPaths is the canonical list of $HOME-relative paths that
// Home Manager projects as symlinks; collisions with real files/dirs
// at these locations need quarantining before activation. Each entry
// must match a `home.file` or `xdg.configFile` target in modules/, at the
// same directory/file granularity. Apply, the wizard, and backup share it.
var trackedPaths = []string{
	".config/ghostty",
	".config/zellij/config.kdl",
	".config/fish/config.fish",
	".config/starship.toml",
	".config/nvim",
	".config/git/config",
	".zshrc",
	".bashrc",
	".bash_profile",
	// .profile is generated by Home Manager regardless of which shell
	// modules are enabled — it sources hm-session-vars and is shell-
	// agnostic. Without it here the snapshot pass leaves a regular
	// $HOME/.profile in place and `checkNewGenCollision` aborts the
	// activation script with no useful nh-side log.
	".profile",
}

type collision struct {
	rel  string
	abs  string
	kind string // "file" | "dir"
}

// findCollisions returns paths that exist as real files/dirs (not symlinks).
// Symlinks at any component below home are left alone, including unmanaged
// links; the snapshotter must never move files through a directory alias.
func findCollisions(home string) ([]collision, error) {
	var out []collision
	for _, rel := range trackedPaths {
		c, err := collisionAt(home, rel)
		if err != nil {
			return nil, err
		}
		if c != nil {
			out = append(out, *c)
		}
	}
	return out, nil
}

// Lstat only avoids following the final component. Check every component
// below home so directory symlinks never expose repository files as
// brownfield collisions. home itself may be an OS-provided alias.
func collisionAt(home, rel string) (*collision, error) {
	if !filepath.IsLocal(rel) || filepath.Clean(rel) != rel || rel == "." {
		return nil, fmt.Errorf("invalid collision path %q", rel)
	}
	abs := home
	var info os.FileInfo
	for _, part := range strings.Split(rel, string(filepath.Separator)) {
		abs = filepath.Join(abs, part)
		var err error
		info, err = os.Lstat(abs)
		if os.IsNotExist(err) {
			return nil, nil
		}
		if err != nil {
			return nil, fmt.Errorf("lstat %s: %w", abs, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil, nil
		}
	}
	kind := "file"
	if info.IsDir() {
		kind = "dir"
	}
	return &collision{rel: rel, abs: abs, kind: kind}, nil
}

func runScan() int {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "cannot resolve $HOME:", err)
		return 1
	}
	cs, err := findCollisions(home)
	if err != nil {
		fmt.Fprintln(os.Stderr, "scan failed:", err)
		return 1
	}
	if len(cs) == 0 {
		fmt.Println("✓ No brownfield collisions on tracked paths. Safe to deploy.")
		fmt.Println("  Untracked HM-managed paths fall back to home-manager's --backup-extension")
		fmt.Println("  (renamed `<file>.backup` next to the original) so activation never aborts.")
		return 0
	}
	fmt.Printf("Found %d collision(s):\n", len(cs))
	for _, c := range cs {
		fmt.Printf("  • [%s] %s\n", c.kind, c.rel)
	}
	fmt.Println()
	fmt.Println("Run `dots backup` to quarantine these to ~/.dots_backups/<ts>/, or")
	fmt.Println("`dots apply` (snapshots them automatically as a plan step).")
	return 0
}
