package main

import (
	"fmt"
	"os"
	"path/filepath"
)

// trackedPaths is the canonical list of $HOME-relative paths that
// Home Manager projects as symlinks; collisions with real files/dirs
// at these locations need quarantining before activation. Each entry
// must match a `home.file."..."` source in modules/. `dots backup` is
// the only entry point and reads directly from this slice; a previous
// duplicate listing in modules/scripts/backup.sh was retired.
var trackedPaths = []string{
	".config/ghostty/config",
	".config/zellij/config.kdl",
	".config/fish/config.fish",
	".config/starship.toml",
	".config/nvim/init.lua",
	".config/git/config",
	".zshrc",
	".bashrc",
	".bash_profile",
	// .profile is generated by Home Manager regardless of which shell
	// modules are enabled — it sources hm-session-vars and is shell-
	// agnostic. Without it here the snapshot pass leaves a regular
	// $HOME/.profile in place and `checkNewGenCollision` aborts the
	// activation script with no useful nh-side log.
	".profile",
}

type collision struct {
	rel  string
	abs  string
	kind string // "file" | "dir"
}

// findCollisions returns paths that exist as real files/dirs (not symlinks).
// A pre-existing symlink is assumed to be a previous Home Manager activation
// and is left alone — Home Manager will rewrite it.
func findCollisions(home string) ([]collision, error) {
	var out []collision
	for _, rel := range trackedPaths {
		abs := filepath.Join(home, rel)
		info, err := os.Lstat(abs)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("lstat %s: %w", abs, err)
		}
		if info.Mode()&os.ModeSymlink != 0 {
			continue
		}
		kind := "file"
		if info.IsDir() {
			kind = "dir"
		}
		out = append(out, collision{rel: rel, abs: abs, kind: kind})
	}
	return out, nil
}

func runScan() int {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "cannot resolve $HOME:", err)
		return 1
	}
	cs, err := findCollisions(home)
	if err != nil {
		fmt.Fprintln(os.Stderr, "scan failed:", err)
		return 1
	}
	if len(cs) == 0 {
		fmt.Println("✓ No brownfield collisions on tracked paths. Safe to deploy.")
		fmt.Println("  Untracked HM-managed paths fall back to home-manager's --backup-extension")
		fmt.Println("  (renamed `<file>.backup` next to the original) so activation never aborts.")
		return 0
	}
	fmt.Printf("Found %d collision(s):\n", len(cs))
	for _, c := range cs {
		fmt.Printf("  • [%s] %s\n", c.kind, c.rel)
	}
	fmt.Println()
	fmt.Println("Run `dots backup` to quarantine these to ~/.dots_backups/<ts>/, or")
	fmt.Println("`dots apply` (snapshots them automatically as a plan step).")
	return 0
}
