package main

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"syscall"
)

type managedHomePath struct {
	rel                string
	allowRealDirectory bool
}

// managedHomePaths returns the canonical $HOME-relative paths that dots owns
// through Home Manager or an activation hook. Most entries become symlinks;
// Ghostty's parent directories remain real so its direct child links work even
// while /nix is unavailable.
func managedHomePaths(goos string) []managedHomePath {
	paths := []managedHomePath{
		{rel: ".config/ghostty", allowRealDirectory: true},
		{rel: ".config/ghostty/shaders"},
		{rel: ".config/ghostty/themes"},
		{rel: ".config/zellij/config.kdl"},
		{rel: ".config/fish/config.fish"},
		{rel: ".config/starship.toml"},
		{rel: ".config/nvim"},
		{rel: ".config/git/config"},
		{rel: ".zshrc"},
		{rel: ".bashrc"},
		{rel: ".bash_profile"},
		// .profile is generated by Home Manager regardless of which shell
		// modules are enabled — it sources hm-session-vars and is shell-
		// agnostic. Without it here the snapshot pass leaves a regular
		// $HOME/.profile in place and `checkNewGenCollision` aborts the
		// activation script with no useful nh-side log.
		{rel: ".profile"},
	}

	if goos == "darwin" {
		return append(paths,
			managedHomePath{rel: "Library/Application Support/com.mitchellh.ghostty", allowRealDirectory: true},
			managedHomePath{rel: "Library/Application Support/com.mitchellh.ghostty/config.ghostty"},
		)
	}
	return append(paths, managedHomePath{rel: ".config/ghostty/config.ghostty"})
}

type collision struct {
	rel  string
	abs  string
	kind string // "file" | "dir"
}

// findCollisions returns paths that exist as real files/dirs (not symlinks).
// A pre-existing symlink is assumed to be a previous dots projection and is
// left alone — Home Manager or the owning activation hook will rewrite it.
func findCollisions(home string) ([]collision, error) {
	var out []collision
	for _, managed := range managedHomePaths(runtime.GOOS) {
		abs := filepath.Join(home, managed.rel)
		info, err := os.Lstat(abs)
		if err != nil {
			// ENOTDIR means an earlier managed parent is a file. That parent
			// is already reported as the actionable collision.
			if os.IsNotExist(err) || errors.Is(err, syscall.ENOTDIR) {
				continue
			}
			return nil, fmt.Errorf("lstat %s: %w", abs, err)
		}
		if info.Mode()&os.ModeSymlink != 0 || managed.allowRealDirectory && info.IsDir() {
			continue
		}
		kind := "file"
		if info.IsDir() {
			kind = "dir"
		}
		out = append(out, collision{rel: managed.rel, abs: abs, kind: kind})
	}
	return out, nil
}

func runScan() int {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintln(os.Stderr, "cannot resolve $HOME:", err)
		return 1
	}
	cs, err := findCollisions(home)
	if err != nil {
		fmt.Fprintln(os.Stderr, "scan failed:", err)
		return 1
	}
	if len(cs) == 0 {
		fmt.Println("✓ No brownfield collisions on tracked paths. Safe to deploy.")
		fmt.Println("  Untracked HM-managed paths fall back to home-manager's --backup-extension")
		fmt.Println("  (renamed `<file>.backup` next to the original) so activation never aborts.")
		return 0
	}
	fmt.Printf("Found %d collision(s):\n", len(cs))
	for _, c := range cs {
		fmt.Printf("  • [%s] %s\n", c.kind, c.rel)
	}
	fmt.Println()
	fmt.Println("Run `dots backup` to quarantine these to ~/.dots_backups/<ts>/, or")
	fmt.Println("`dots apply` (snapshots them automatically as a plan step).")
	return 0
}
